### ISSUE TITLE
(Remove|Keep) old strings

### ISSUE THREAD

**Issue by meysampg** [kevinchappell/formBuilder-languages#4]
There are some differences between new `en-Us.lang` file and some older files (in this case `fa-Ir.lang` which I'm translating new strings on it) which are in this types:

1. Changes:
For example:
```
< class 
---
> className 
```
`class` is an old string in Farsi translation which I think it updated to `className` on new version of English file.

2. Removes:
`allowSelect` exists on Farsi translation which removed in new English version.

3. New Expressions:
`value` is a new expression which is added to new version.

For 3 the problem is solved, They must be translated. But for 1 and 2 what's the general norm? Keep them (for save BC :thinking:) or just update translation file one-to-one of English file :100:?

**Comment by kevinchappell** [comment]
If they are unused I think they can be updated, added or removed. These language files only work in 2.x and there is no class string in 2.x. The impact should be minimal.

**Comment by meysampg** [comment]
Well and just another little question. Are languages merged into class file? or they must be loaded on demand? If it's merged, I (and everyone whom make a package based on formbuilder) can referrer on [yii2-formbuilder](https://github.com/meysampg/yii2-formbuilder) to this repository to add or update language and remove my message handling. Hum?

**Comment by kevinchappell** [comment]
All changes made in this repo are used by formBuilder but language files are not merged to the plugin. In formBuilder 2.x you have the option of defining a location to language files. This location can be in your project which could contain a fork of this repo or custom language files but defaults​ to the formBuilder website. So unless the setting is overridden any string translations merged to this repo will appear in formBuilder. For example if you were to update fa-IR.lang, the changes would appear on formbuilder.online and any running instance that does not have their own fa-IR.lang

It's also possible to set an `i18n.preloaded` option so translations are not remotely loaded.

So to answer your question more directly, yes. this is the repo for all formbuilder string translations.

**Comment by meysampg** [comment]
Well, It's great! Thanks!
