### ISSUE TITLE
Bug in checkbox edit mode

### ISSUE THREAD

**Issue by dpow40** [kevinchappell/formBuilder-languages#45]
There's a typo when you add a checkbox to the form. See attached photo:

![image](https://user-images.githubusercontent.com/9360905/66950052-a9848000-f025-11e9-8ba0-dd66f90bde49.png)

**Comment by dpow40** [comment]
I created a pull request for the fix @kevinchappell  :)

**Comment by lucasnetau** [comment]
Closed By: #46
