### ISSUE TITLE
Suddenly getting this error. It was working perfect before..

### ISSUE THREAD

**Issue by Hasnni** [kevinchappell/formBuilder-languages#84]
Hello .
Suddenly i am getting this error i dont know what happend i even didnot change anything.
assets/lang/en-US.lang:1 Failed to load resource: the server responded with a status of 404 ():
![error](https://user-images.githubusercontent.com/16034072/123782678-dfd76100-d8d5-11eb-96cd-5715aa8c8335.png)

What should i do now . I am using Jquery Formbuilder 3.6.1 version

**Comment by kevinchappell** [comment]
@Hasnni can you share the url for the missing file?

**Comment by Hasnni** [comment]
@kevinchappell  Thank you so much for your reply. I am using formBuilder.min.js 3.6.1 version.
here is link of error. Its automatically getting this error.
 https://localhost:44338/Configuration/assets/lang/en-US.lang

**Comment by kevinchappell** [comment]
@Hasnni can you share the formBuilder options used?

**Comment by Hasnni** [comment]
@kevinchappell  here is the options which i used.
` options = {
                            //disabledActionButtons: ['save'],
                            showActionButtons: false,
                            editOnAdd: true,
                            stickyControls: {
                                enable: true
                            },
                            formData: forata,
                            dataType: 'json'
                        };`

**Comment by kevinchappell** [comment]
i dont see anything there that should cause this. can you create a jsFiddle or codepen that reproduces the error?

**Comment by Hasnni** [comment]
@kevinchappell  code is working fine now as well with these errors .just these errors coming in console. Automatically these errors coming now days before it was working fine with no errors.

**Comment by Hasnni** [comment]
@kevinchappell how can we get this lang file in formbuilder options .?

**Comment by kevinchappell** [comment]
@Hasnni English is loaded by default and is in formBuilder without need for a separate file. You can try explicitly setting the location of your language files to a known working location in your formBuilder options:

```javascript
i18n: {
  location: 'https://formbuilder.online/assets/lang/'
},
```

**Comment by Hasnni** [comment]
@kevinchappell  Thank you its working.
